services:
  bd_mysql:
    container_name: bd_mysql
    image: mysql:9.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bd_base
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./bd_biblioteca.sql:/docker-entrypoint-initdb.d/bd_biblioteca.sql
  
  bd_phpmyadmin:
    container_name: bd_phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - bd_mysql
    ports:
      - "8888:80"
    environment:
      PMA_HOST: bd_mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root

volumes:
  mysql_data: